---
kind: pipeline
type: docker
name: school

steps:
- name: submodules
  image: alpine/git
  commands:
  - git submodule update --init --recursive

- name: restore-cache
  image: drillster/drone-volume-cache
  volumes:
  - name: cache
    path: /cache
  settings:
    restore: true
    mount:
      - ./node_modules

- name: website
  image: node:18
  commands:
  - apt-get update && apt-get install rsync -y build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
  - mkdir -p $HOME/.ssh
  - ssh-keyscan -t rsa github.com >> $HOME/.ssh/known_hosts
  - echo "$GITHUB_PRIVATE_KEY" > "$HOME/.ssh/id_rsa"
  - chmod 0600 $HOME/.ssh/id_rsa
  - yarn install --frozen-lockfile
  - npm run sync
  - npm run deploy
  environment:
    USE_SSH: true
    WITHOUT_DOCS: "true"
    GIT_USER: $DRONE_COMMIT_AUTHOR
    NODE_OPTIONS: "--max_old_space_size=12288"
    GITHUB_PRIVATE_KEY:
      from_secret: "git_deploy_private_key"
    AZURE_CLIENT_ID:
      from_secret: "AZURE_CLIENT_ID"
    UMAMI_SRC:
      from_secret: "UMAMI_SRC"
    UMAMI_ID:
      from_secret: "UMAMI_ID"
    DOMAIN:
      from_secret: "DOMAIN"
    ALGOLIA_APP_ID:
      from_secret: "ALGOLIA_APP_ID"
    ALGOLIA_API_KEY:
      from_secret: "ALGOLIA_API_KEY"
    ALGOLIA_INDEX_NAME:
      from_secret: "ALGOLIA_INDEX_NAME"
  when:
    event:
      include:
      - push
      - pull_request

- name: rebuild-cache
  image: drillster/drone-volume-cache
  volumes:
  - name: cache
    path: /cache
  settings:
    rebuild: true
    mount:
      - ./node_modules

- name: notify
  image: plugins/webhook
  settings:
    urls:
      from_secret: NODE_RED_WEBHOOK
  when:
    status:
    - success
    - failure

volumes:
  - name: cache
    host: 
      path: /var/lib/dokku/data/storage/hfr-drone-runner/cache

trigger:
  branch:
  - main

---
kind: pipeline
type: docker
name: all-docs

steps:

- name: submodules
  image: alpine/git
  commands:
  - git submodule update --init --recursive
- name: restore-cache
  image: drillster/drone-volume-cache
  volumes:
  - name: cache
    path: /cache
  settings:
    restore: true
    mount:
      - ./node_modules

- name: website
  image: node:18
  commands:
  - apt-get update && apt-get install rsync -y build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
  - mkdir -p $HOME/.ssh
  - ssh-keyscan -t rsa github.com >> $HOME/.ssh/known_hosts
  - echo "$GITHUB_PRIVATE_KEY" > "$HOME/.ssh/id_rsa"
  - chmod 0600 $HOME/.ssh/id_rsa
  - yarn install --frozen-lockfile
  - npm run sync
  - npm run deploy
  environment:
    USE_SSH: true
    GIT_USER: $DRONE_COMMIT_AUTHOR
    NODE_OPTIONS: "--max_old_space_size=12288"
    GITHUB_PRIVATE_KEY:
      from_secret: "git_deploy_private_key_docs"
    UMAMI_SRC:
      from_secret: "UMAMI_SRC"
    AZURE_CLIENT_ID:
      from_secret: "AZURE_CLIENT_ID"
    UMAMI_ID:
      from_secret: "UMAMI_ID"
    DOMAIN:
      from_secret: "DOCS_DOMAIN"
    DOCS_ONLY: "true"
    GH_PROJECT: "ofi-blog-docs"
    ALGOLIA_APP_ID: "KAXH1Q07BI"
    ALGOLIA_API_KEY: "dce94e1097cc40d352060a9fe4b31154"
    ALGOLIA_INDEX_NAME: "ofi-gbsl1"
  when:
    event:
      include:
      - push
      - pull_request

volumes:
  - name: cache
    host: 
      path: /var/lib/dokku/data/storage/hfr-drone-runner/cache

trigger:
  branch:
  - main